### ISSUE TITLE
[Bug]: Individual contributors pages do not show the picture

### ISSUE THREAD

**Issue by albertocottica** [UNDP-Accelerator-Labs/Financial-inclusion-toolkit#1]
### Issue description

For example, Amanuel's picture shows up in the general Contributors page, but not in his own: 
https://undp-accelerator-labs.github.io/Financial-inclusion-toolkit/contributors/Amanuel-Tadesse.html

### Where did this happen?

https://undp-accelerator-labs.github.io/Financial-inclusion-toolkit/contributors/Amanuel-Tadesse.html

### What do you expect?

To see the picture

**Comment by this-pama** [comment]
Fixed.
